name = "kleepee-v1"
main = "worker/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "SESSION_DO"
class_name = "SessionDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SessionDurableObject"]

[env.production]
name = "kleepee-v1-production"
workers_dev = true
routes = [
  { pattern = "kleepee-worker.adelekecode.dev/*", zone_name = "adelekecode.dev" }
]

[[env.production.durable_objects.bindings]]
name = "SESSION_DO"
class_name = "SessionDurableObject"

[[env.production.migrations]]
tag = "v1"
new_sqlite_classes = ["SessionDurableObject"]
